export const logo_url =
  "https://cdn.cookielaw.org/logos/dd6b162f-1a32-456a-9cfe-897231c7763c/4345ea78-053c-46d2-b11e-09adaef973dc/Netflix_Logo_PMS.png";

export const API_OPTIONS = {
  method: "GET",
  headers: {
    accept: "application/json",
    Authorization:
      "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzMDY5MDI3NWE3ZGVjZTExYzRhZWQ4ZjFhOTM4YTY4NiIsInN1YiI6IjY1ZWVhZGVkZjVjYjIxMDE2MjQ1MGE4NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.i9XeSIhJpNOOoGk83EEOzCWNjh2T9UhNMX9z2Kdm96s",
  },
};

export const DUMMY_NOW_PLAYING_MOVIES = [
  {
    adult: false,
    backdrop_path: "/mDeUmPe4MF35WWlAqj4QFX5UauJ.jpg",
    genre_ids: [28, 27, 53],
    id: 1096197,
    original_language: "pt",
    original_title: "No Way Up",
    overview:
      "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
    popularity: 1425.033,
    poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
    release_date: "2024-01-18",
    title: "No Way Up",
    video: false,
    vote_average: 6.007,
    vote_count: 203,
  },
  {
    adult: false,
    backdrop_path: "/gJL5kp5FMopB2sN4WZYnNT5uO0u.jpg",
    genre_ids: [28, 12, 16, 35, 10751],
    id: 1011985,
    original_language: "en",
    original_title: "Kung Fu Panda 4",
    overview:
      "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    popularity: 1652.671,
    poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    release_date: "2024-03-02",
    title: "Kung Fu Panda 4",
    video: false,
    vote_average: 6.9,
    vote_count: 67,
  },
  {
    adult: false,
    backdrop_path: "/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
    genre_ids: [878, 10749, 35],
    id: 792307,
    original_language: "en",
    original_title: "Poor Things",
    overview:
      "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
    popularity: 1405.876,
    poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    release_date: "2023-12-07",
    title: "Poor Things",
    video: false,
    vote_average: 7.905,
    vote_count: 2106,
  },
  {
    adult: false,
    backdrop_path: "/ekRp1sEA8pnuzVHQkUESTgNSKdW.jpg",
    genre_ids: [878, 28, 80],
    id: 932420,
    original_language: "en",
    original_title: "Code 8 Part II",
    overview:
      "In a world where superpowered people are heavily policed by robots, an ex-con teams up with a drug lord he despises to protect a teen from a corrupt cop.",
    popularity: 1156.526,
    poster_path: "/hhvMTxlTZtnCOe7YFhod9uz3m37.jpg",
    release_date: "2024-02-27",
    title: "Code 8 Part II",
    video: false,
    vote_average: 6.654,
    vote_count: 257,
  },
  {
    adult: false,
    backdrop_path: "/3Kzc6V4MWs3RXCmE5DhAYnfWL8F.jpg",
    genre_ids: [16, 35, 878],
    id: 1239251,
    original_language: "en",
    original_title: "Megamind vs. the Doom Syndicate",
    overview:
      "Megamind's former villain team, The Doom Syndicate, has returned. Our newly crowned blue hero must now keep up evil appearances until he can assemble his friends (Roxanne, Ol' Chum and Keiko) to stop his former evil teammates from launching Metro City to the Moon.",
    popularity: 1238.185,
    poster_path: "/1N7terrMeZPwK5qq31MUD0HQ3IG.jpg",
    release_date: "2024-03-01",
    title: "Megamind vs. the Doom Syndicate",
    video: false,
    vote_average: 5.529,
    vote_count: 102,
  },
  {
    adult: false,
    backdrop_path: "/xvk5AhfhgQcTuaCQyq3XqAnhEma.jpg",
    genre_ids: [28, 12, 35],
    id: 848538,
    original_language: "en",
    original_title: "Argylle",
    overview:
      "When the plots of reclusive author Elly Conway's fictional espionage novels begin to mirror the covert actions of a real-life spy organization, quiet evenings at home become a thing of the past. Accompanied by her cat Alfie and Aiden, a cat-allergic spy, Elly races across the world to stay one step ahead of the killers as the line between Conway's fictional world and her real one begins to blur.",
    popularity: 1636.918,
    poster_path: "/95VlSEfLMqeX36UVcHJuNlWEpwf.jpg",
    release_date: "2024-01-31",
    title: "Argylle",
    video: false,
    vote_average: 6.115,
    vote_count: 511,
  },
  {
    adult: false,
    backdrop_path: "/f6ahdeUZPwUVirr86gcZ1QmiasQ.jpg",
    genre_ids: [878, 12],
    id: 693134,
    original_language: "en",
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    popularity: 958.944,
    poster_path: "/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    release_date: "2024-02-27",
    title: "Dune: Part Two",
    video: false,
    vote_average: 8.426,
    vote_count: 1464,
  },
  {
    adult: false,
    backdrop_path: "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
    genre_ids: [16, 28, 12, 35, 10751],
    id: 940551,
    original_language: "en",
    original_title: "Migration",
    overview:
      "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
    popularity: 909.36,
    poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    release_date: "2023-12-06",
    title: "Migration",
    video: false,
    vote_average: 7.555,
    vote_count: 914,
  },
  {
    adult: false,
    backdrop_path: "/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg",
    genre_ids: [28, 53, 10752],
    id: 969492,
    original_language: "en",
    original_title: "Land of Bad",
    overview:
      "When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.",
    popularity: 827.79,
    poster_path: "/lYwjlcBjokC9EhfzfAOkTMQd5Ku.jpg",
    release_date: "2024-01-25",
    title: "Land of Bad",
    video: false,
    vote_average: 6.9,
    vote_count: 323,
  },
  {
    adult: false,
    backdrop_path: "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 984.963,
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    video: false,
    vote_average: 8.115,
    vote_count: 7094,
  },
  {
    adult: false,
    backdrop_path: "/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg",
    genre_ids: [35, 10749],
    id: 1072790,
    original_language: "en",
    original_title: "Anyone But You",
    overview:
      "After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
    popularity: 684.389,
    poster_path: "/5qHoazZiaLe7oFBok7XlUhg96f2.jpg",
    release_date: "2023-12-21",
    title: "Anyone But You",
    video: false,
    vote_average: 6.997,
    vote_count: 942,
  },
  {
    adult: false,
    backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    genre_ids: [878, 12],
    id: 438631,
    original_language: "en",
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    popularity: 601.52,
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    release_date: "2021-09-15",
    title: "Dune",
    video: false,
    vote_average: 7.786,
    vote_count: 10684,
  },
  {
    adult: false,
    backdrop_path: "/824e60sDlEXUP1vXCYNqh5RSlI5.jpg",
    genre_ids: [878, 12, 18],
    id: 636706,
    original_language: "en",
    original_title: "Spaceman",
    overview:
      "During a research mission, an astronaut discovers that his marriage is in trouble. Luckily, he has the help of a mysterious creature hidden in his ship.",
    popularity: 475.99,
    poster_path: "/jDdnDEGu3GiLtJwDXeL4hfFzmGv.jpg",
    release_date: "2024-02-23",
    title: "Spaceman",
    video: false,
    vote_average: 6.667,
    vote_count: 313,
  },
  {
    adult: false,
    backdrop_path: "/xi2pblvQtCnh26SeOYzx1YX3DLT.jpg",
    genre_ids: [80, 28, 53],
    id: 1227816,
    original_language: "en",
    original_title: "Red Right Hand",
    overview:
      "Cash is trying to live a quiet, honest life in a small Appalachian town. When a vicious crime boss forces him back into her services, he soon learns he's capable of anything -- even killing -- to protect his family and his home.",
    popularity: 519.22,
    poster_path: "/vfEG79SQIg3p6B8rBLVeIo2BBhb.jpg",
    release_date: "2024-02-22",
    title: "Red Right Hand",
    video: false,
    vote_average: 7,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: "/midCh3iVxaG3dUOrP9TnUpNcGm.jpg",
    genre_ids: [16, 12, 14],
    id: 508883,
    original_language: "ja",
    original_title: "君たちはどう生きるか",
    overview:
      "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
    popularity: 526.429,
    poster_path: "/jDQPkgzerGophKRRn7MKm071vCU.jpg",
    release_date: "2023-07-14",
    title: "The Boy and the Heron",
    video: false,
    vote_average: 7.475,
    vote_count: 1041,
  },
  {
    adult: false,
    backdrop_path: "/cu5Qk2QHxOyyMrD3Bq93DxgmJer.jpg",
    genre_ids: [28, 80],
    id: 1046090,
    original_language: "zh",
    original_title: "周處除三害",
    overview:
      "The arrogant, third most-wanted criminal in Taiwan, decides to get rid of the top two competitors and crowns himself the most-wanted criminal before dying.",
    popularity: 750.41,
    poster_path: "/7IJ7F8tX7IAkpUdaGovOBJqORnJ.jpg",
    release_date: "2023-10-06",
    title: "The Pig, the Snake and the Pigeon",
    video: false,
    vote_average: 7.708,
    vote_count: 72,
  },
  {
    adult: false,
    backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
    genre_ids: [28, 53, 18],
    id: 866398,
    original_language: "en",
    original_title: "The Beekeeper",
    overview:
      "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
    popularity: 533.011,
    poster_path: "/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
    release_date: "2024-01-08",
    title: "The Beekeeper",
    video: false,
    vote_average: 7.463,
    vote_count: 1668,
  },
  {
    adult: false,
    backdrop_path: "/deLWkOLZmBNkm8p16igfapQyqeq.jpg",
    genre_ids: [14, 12, 28],
    id: 763215,
    original_language: "en",
    original_title: "Damsel",
    overview:
      "A young woman's marriage to a charming prince turns into a fierce fight for survival when she's offered up as a sacrifice to a fire-breathing dragon.",
    popularity: 724.045,
    poster_path: "/sMp34cNKjIb18UBOCoAv4DpCxwY.jpg",
    release_date: "2024-03-08",
    title: "Damsel",
    video: false,
    vote_average: 7.368,
    vote_count: 509,
  },
  {
    adult: false,
    backdrop_path: "/aPQsU3yLDUOhLJYnSqkhKRkQTAw.jpg",
    genre_ids: [36, 18, 10752],
    id: 467244,
    original_language: "en",
    original_title: "The Zone of Interest",
    overview:
      "The commandant of Auschwitz, Rudolf Höss, and his wife Hedwig, strive to build a dream life for their family in a house and garden next to the camp.",
    popularity: 359.032,
    poster_path: "/hUu9zyZmDd8VZegKi1iK1Vk0RYS.jpg",
    release_date: "2023-12-15",
    title: "The Zone of Interest",
    video: false,
    vote_average: 7.313,
    vote_count: 772,
  },
  {
    adult: false,
    backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
    genre_ids: [16, 10751, 14, 12],
    id: 1022796,
    original_language: "en",
    original_title: "Wish",
    overview:
      "Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
    popularity: 391.486,
    poster_path: "/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg",
    release_date: "2023-11-13",
    title: "Wish",
    video: false,
    vote_average: 6.611,
    vote_count: 858,
  },
];

// filter trailer from this
export const FIRST_MOVIE_VIDEOS = [
  {
    iso_639_1: "en",
    iso_3166_1: "US",
    name: "Clip",
    key: "UJa1zUYegqo",
    site: "YouTube",
    size: 1080,
    type: "Clip",
    official: true,
    published_at: "2024-02-16T16:31:54.000Z",
    id: "65d40e001d356301631e68cb",
  },
  {
    iso_639_1: "en",
    iso_3166_1: "US",
    name: "Official Trailer",
    key: "e1k1PC0TtmE",
    site: "YouTube",
    size: 1080,
    type: "Trailer",
    official: true,
    published_at: "2023-11-30T13:02:56.000Z",
    id: "65880cfc5aba326759b95156",
  },
];
